//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.9145
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.9145.
// 
namespace SmartDeviceProject.WebReference {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    using System.Data;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebService_kanbanSoap", Namespace="http://tempuri.org/")]
    public partial class WebService_kanban : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public WebService_kanban() {
            this.Url = "http://172.16.16.1/handheld_webservice/WebService_kanban.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/insert_data_to_db_from_local", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void insert_data_to_db_from_local(string partnumber, string srctcode, string dockcode, int pack, string error, string chk, string user, System.DateTime day, string ekb, string kbid) {
            this.Invoke("insert_data_to_db_from_local", new object[] {
                        partnumber,
                        srctcode,
                        dockcode,
                        pack,
                        error,
                        chk,
                        user,
                        day,
                        ekb,
                        kbid});
        }
        
        /// <remarks/>
        public System.IAsyncResult Begininsert_data_to_db_from_local(string partnumber, string srctcode, string dockcode, int pack, string error, string chk, string user, System.DateTime day, string ekb, string kbid, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("insert_data_to_db_from_local", new object[] {
                        partnumber,
                        srctcode,
                        dockcode,
                        pack,
                        error,
                        chk,
                        user,
                        day,
                        ekb,
                        kbid}, callback, asyncState);
        }
        
        /// <remarks/>
        public void Endinsert_data_to_db_from_local(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/get_m_kanban", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable get_m_kanban() {
            object[] results = this.Invoke("get_m_kanban", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginget_m_kanban(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("get_m_kanban", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataTable Endget_m_kanban(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/get_srct_kanban", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable get_srct_kanban(string ekanban, string loca, string dock) {
            object[] results = this.Invoke("get_srct_kanban", new object[] {
                        ekanban,
                        loca,
                        dock});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginget_srct_kanban(string ekanban, string loca, string dock, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("get_srct_kanban", new object[] {
                        ekanban,
                        loca,
                        dock}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataTable Endget_srct_kanban(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/login", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable login(string username) {
            object[] results = this.Invoke("login", new object[] {
                        username});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginlogin(string username, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("login", new object[] {
                        username}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataTable Endlogin(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataTable)(results[0]));
        }
    }
}
